name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Set up PostgreSQL service for tests
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set up environment
        run: |
          # Create test database
          PGPASSWORD=postgres psql -h localhost -U postgres -c 'CREATE DATABASE recurse_bookings_test;'

          # Create .env.test file with correct GitHub Actions PostgreSQL credentials
          cat > .env.test << EOF
          VITE_DB_USER=postgres
          VITE_DB_HOST=localhost
          VITE_DB_NAME=recurse_bookings_test
          VITE_DB_PASSWORD=postgres
          VITE_DB_PORT=5432
          VITE_DB_SSL=false
          VITE_RECURSE_CLIENT_ID=test_client_id
          VITE_RECURSE_CLIENT_SECRET=test_client_secret
          VITE_OAUTH_REDIRECT_URI=http://localhost:5173/oauth/callback
          EOF

          # Copy .env.test to .env for compatibility
          cp .env.test .env

          # Run the test database setup script
          npm run setup:test-db

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run API tests
        run: npm run test:api
        env:
          PLAYWRIGHT_JUNIT_OUTPUT_NAME: results/junit-api.xml

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            playwright-report/
            test-results/
